name: Update Weather Data

on:
  schedule:
    - cron: '0 * * * *' # Körs automatiskt varje heltimme
  workflow_dispatch: # Gör att du kan starta den manuellt med en knapp!

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    # Detta ger roboten fulla rättigheter att spara filer i ditt arkiv
    permissions:
      contents: write
      
    steps:
      - name: Klonar arkiv
        uses: actions/checkout@v4

      - name: Installerar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Hämtar väderdata
        run: node fetch-weather.js

      - name: Sparar data till GitHub Arkiv
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@://github.com'
          git add weather.json
          git commit -m "Automatiskt uppdaterad väderdata" || echo "Inga ändringar att spara"
          git push
